### ISSUE TITLE
怎么加密混淆ssr能够缓解被g@wf封禁呢？

### ISSUE THREAD

**Issue by yakiler** [Jiang-Xuan/deepinss#40]
您好，我也是一名开发人员，前段时间购买了班瓦工，尝试自己搭建了ssr 并取得成功。我尝试了访问google，fb。然后就下线了，关掉了ssr客户端（一般使用才开）。但是没过2天我就发现Ip被河蟹了。我搭建ssr都时候还是选择了加密和混淆的，不知道倒是不记得用了哪种加密混淆方式，想请教您有哪些方式能够改善这种情况呢？尤其是使用哪种方式加密和混淆会好些？
非常感谢您

**Comment by Jiang-Xuan** [comment]
`aes-256-cfb` 我个人使用的加密算法, 用的 linode 服务器, 并且我一般的流量都是走a里yun中转的. 如果封的比较厉害, 可以尝试走a里yun中转, 至少可以*躲*地方运营商的**,

**Comment by yakiler** [comment]
‘走a里yun中转’  请问这个是什么意思？不太懂

**Comment by Jiang-Xuan** [comment]
流量让阿里云的服务器中转一下, 我向阿里云服务器发起请求, 而不是国外的服务器, 阿里云的服务器负责和国外的服务器通讯

**Comment by yakiler** [comment]
非常感谢大佬指点，是不是要买个ali服务器，在ali服务器上再安装一个ssr客户端用来访问国外vps，同时ali服务器也安装ssr服务端用来处理本地请求。 
另外混淆用哪个类型比较好呢？

**Comment by Jiang-Xuan** [comment]
@yakiler 不要在阿里云上面装 ssr, 很容易会被发现, 给你推荐一个端口转发工具, [socat](http://www.dest-unreach.org/socat/doc/socat.html). 混淆工具我目前没有使用, 不过每周6我的 linode 会自动更改端口. 这种方式运行了好长时间了, 目前还没有被封过.

**Comment by yakiler** [comment]
ok , thank you.
